collections:
  photographs:
    output: true

defaults:
  - scope:
      path: ""
      type: "photographs"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"